import argparse
from codenamesbot import CodenamesBot

parser = argparse.ArgumentParser()
parser.add_argument("--encodings", type=str, required=True, help="Path to encodings file generated by the 'generateencodings.py' script")
parser.add_argument("--team", type=str, required=True, help="Team to play for ('blue' or 'red')")
args = parser.parse_args()

# Defines the words in the game
game = {
    "blue": ["hospital", "ladrão", "massa", "afoito", "exame", "tinta", "açúcar", "cabana"],
    "red": ["sirene", "muro", "fantasma", "castelo", "dura", "tela", "libra", "paris", "nervo"],
    "gray": ["talco", "vikings", "paciente", "parada", "santa", "cebola", "peruca"],
    "black": ["licença"]
}

bot = CodenamesBot(game, args.team, args.encodings)
bot.initialize()
bot.print_best_guesses()